# Generated by Django 3.2.2 on 2021-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('telephone', models.TextField(blank=True, null=True)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvancementIndicateurTb',
            fields=[
                ('avancement_indicateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('realisation', models.FloatField()),
                ('annee', models.DateField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'avancement_indicateur_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BassinVersantTb',
            fields=[
                ('bassin_versant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'bassin_versant_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeneficiaireOngTb',
            fields=[
                ('beneficiaire_ong_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'beneficiaire_ong_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeneficiaireTb',
            fields=[
                ('beneficiaire_id', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(max_length=10)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'beneficiaire_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieIndicateur',
            fields=[
                ('categorie_indicateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('valeur_representative', models.FloatField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'categorie_indicateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommuneTb',
            fields=[
                ('commune_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'commune_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartementTb',
            fields=[
                ('departement_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'departement_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtrantTb',
            fields=[
                ('extrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur_representative', models.FloatField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'extrant_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FonctionTb',
            fields=[
                ('fonction_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.TextField()),
            ],
            options={
                'db_table': 'fonction_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicateurOngTb',
            fields=[
                ('indicateur_ong_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'indicateur_ong_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicateurResultatTb',
            fields=[
                ('indicateur_resultat_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur_representative', models.FloatField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'indicateur_resultat_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicateurTb',
            fields=[
                ('indicateur_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('cible', models.FloatField()),
                ('valeur_base', models.FloatField()),
                ('valeur_representative', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'indicateur_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocaliteTb',
            fields=[
                ('localite_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'localite_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OngTb',
            fields=[
                ('ong_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'ong_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RisqueTb',
            fields=[
                ('risque_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'risque_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionCommunaleTb',
            fields=[
                ('section_communale_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'section_communale_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SousExtrantTb',
            fields=[
                ('sous_extrant_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur_representative', models.FloatField()),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'sous_extrant_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('temoignage_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.CharField(max_length=255)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'temoignage',
                'managed': False,
            },
        ),
    ]
