# Generated by Django 3.2.2 on 2021-06-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactTb',
            fields=[
                ('impact_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'impact_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeImpactTb',
            fields=[
                ('type_impact_id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50)),
                ('statut', models.IntegerField()),
            ],
            options={
                'db_table': 'type_impact_tb',
                'managed': False,
            },
        ),
    ]
